name: deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: instalar dependencias
        run: npm i  

      - name: testear
        run: npm run test

      - name: build
        run: npm run build

      - name: subir el artefacto
        uses: action/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

      
    steps:
      - name: deploy
        id: deploy-pages
        uses: actions/deploy-pages@v4