name: passing-information-between-jobs
on: push

# COMPARTIR INFORMACION ENTRE JOBS
jobs: 
  
  first_job:
    runs-on: ubuntu-latest

    # Almacenar en global
    outputs:
      salida: ${{ steps.step_1.outputs.message }}

    steps:
      - name: Crear variable
        id: step_1
        run: echo "message=desde-firts-job" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.message }}"
        
    second_job:
      needs: firts_job
      runs-on: ubuntu-latest

      # Crear variables de entorno y asignar el valor de la referencia
      env:
        SALIDA: ${{ needs.firts_job.outputs.salida }}

      steps:
        - name: Imprimir mensaje
          run: echo "$SALIDA"