name: strategies
on: push

# Estrategias
jobs: 
  
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["version 1", "version 2", "version 3"]

    steps:
      - name: imprimir mensaje
        run: echo " ${{ matrix.message }}"
